### ISSUE TITLE
Preview does not work

### ISSUE THREAD

**Issue by dayoungcheong** [placeholder-team-name/placeholder#1] opened 2019-06-10 23:03 UTC

**Comment by dayoungcheong** [comment] 2019-06-10 23:05
I logged in and started to write in the editor. When I clicked the preview button, nothing shows up and I cannot preview anything I wrote. It shows an empty page with just a "write" and "send" button

**Comment by dayoungcheong** [comment] 2019-06-10 23:06
It only shows the preview if I "save" beforehand, but it does not show things that I bolded in the preview.

**Comment by dayoungcheong** [comment] 2019-06-10 23:08
It also does not show things that are underlined

**Comment by kwokwilliam** [comment] 2019-06-11 06:06
Having it only show up on save is an intended feature. The underlining is an artifact of React-Draft-WYSIWYG, the rich text editor library we are using, and thus is out of scope for our bug fix.

**Comment by kwokwilliam** [comment] 2019-06-11 06:07
The bolded issue is a CSS issue and has been fixed.

**Closed as completed by kwokwilliam** 2019-06-11 06:07 UTC
Labels: invalid, wontfix, Minor, fixed already

**Comment by vincentmvdm** [comment] 2019-06-12 21:50
Some more clarification for Andy & Selene: we believe our preview was working all along. From yesterday's Slack message:

"We require the user to first save their work before it will show up on preview. In other words, this is intended behavior (documented in our requirements) and in this case the user’s mental model didn’t match ours."
