### ISSUE TITLE
After sending a postcard, preview will continue to show that postcard even when changing the form

### ISSUE THREAD

**Issue by bbalansay** [placeholder-team-name/placeholder#25] opened 2019-06-11 16:10 UTC
Make a postcard, save it, preview it and send. After sending, click write and change the data within the form. If you save and preview it, the information should change but doesn't.

**Comment by clairehjk** [comment] 2019-06-12 05:22
Can't seem to reproduce this bug. I've tried sending the information on the second preview/send and it works as intended. Will continue to look out for this behavior but for now closing, as we cannot seem to reproduce it at all.

**Comment by kwokwilliam** [comment] 2019-06-12 05:26
Possible issue is that you may be clicking on the button too fast. We will disable the button while the save is in progress so this doesn't occur.

**Comment by clairehjk** [comment] 2019-06-12 18:54
We have decided to fix this issue by implementing the following changes:

When a user saves -> Button says “Saving…” instead of “Save” -> Also Preview becomes disables until it’s finished saving
https://github.com/placeholder-team-name/postcards/pull/37

**Closed as completed by clairehjk** 2019-06-12 18:54 UTC
Labels: bug, medium importance
