### ISSUE TITLE
Click save also let text color, font, and backgournd color went to default color

### ISSUE THREAD

**Issue by s21dy** [placeholder-team-name/placeholder#17] opened 2019-06-11 04:54 UTC
- I type "How are you"
- I edit the text color and background color of the text
- I click save
- The text color and background went back to normal (black and white)
- But when I went to preview it looks fine.

**Comment by kwokwilliam** [comment] 2019-06-11 06:28
https://github.com/facebook/draft-js/issues/623

Support styles is out of scope because we would have to manually declare the styles for every single possible thing. This is an issue with React draft wysiwyg not supporting styles out of the box for us to use easily.

Even if we use the `userNotebookContent.getCurrentInlineStyle()` function, the documentation is so poor that it doesn't even mention where to set the inline style we get from this obscure object. https://jpuri.github.io/react-draft-wysiwyg/#/docs

**Closed as completed by kwokwilliam** 2019-06-11 06:28 UTC
Labels: wontfix, Cant fix because of react draft wysiwyg

**Comment by kwokwilliam** [comment] 2019-06-11 06:46
#17 is actually a duplicate of #16
