### ISSUE TITLE
Screen when blank after clicking on uploaded photo a few times

### ISSUE THREAD

**Issue by VanelyRuiz** [placeholder-team-name/placeholder#35] opened 2019-06-11 21:38 UTC
![image](https://user-images.githubusercontent.com/35097969/59307293-0ffe2980-8c53-11e9-9e84-5da6f79643a1.png)

I was trying to change the alignment of a photo and everything disappeared. The screenshot shows my blank screen and what was in the console when it happened. 

So I had two photos, one loaded from a file and the other from a url. The file upload photo was large and took up more than the width of the postcard area while the url uploaded photo was smaller. I could change the alignment of the url photo by hovering over it and clicking one of the options: L, C, or R. But the larger photo didn't display these options and I tried clicking on the photo a few times because, at the time, I didn't know you just had to hover over the photo to get those options. After I clicked on the photo about 3 times it just crashed; however, after refreshing the page I was still signed in. It displayed the last save of my postcard so all my changes were obviously gone.

**Comment by kwokwilliam** [comment] 2019-06-12 05:09
Issue is caused by react draft wysiwyg being super stupidly weird about handling images. It is out of scope for this assignment to fix this functionality. I have tried to fix as much image weirdness when programming it in in the first place. This is easily a fix that would take me two entire days to debug.

**Closed as completed by kwokwilliam** 2019-06-12 05:09 UTC
Labels: bug, wontfix, Cant fix because of react draft wysiwyg

**Comment by clairehjk** [comment] 2019-06-12 18:59
Though this is an issue, it's not something that we can fix within the given time because during debugging in our development, we have came across issues with working with the React draft wysiwyg package (https://www.npmjs.com/package/react-draft-wysiwyg) and decided that it wasn't worth our time to work on fixes on this package that would result in minor changes. It is also out of our control of the behavior that this package displays. We have marked all React draft wysiwyg  related issues with the ` Cant fix because of react draft wysiwyg ` tag.
