### ISSUE TITLE
Pressing Save or Preview Removes Styling

### ISSUE THREAD

**Issue by charlyecastro** [placeholder-team-name/placeholder#19] opened 2019-06-11 05:49 UTC
### Preview 
- __Does Not Show__
   - Bold
   - Underline
   - Emoji (Replaced with ??)
- __Does Show__
    - Text Color
    - Italics
     - List Number

### Save 
- __Does Not Show__
    - Text Color
    - Emoji (Replaced with ??)
    - Underline
- __Does Show__
     - Bold
     - Italics
     - List Number

### Gif of Problem
![2019-06-10 22 28 34](https://user-images.githubusercontent.com/24886389/59245924-80fbfd80-8bcf-11e9-9580-ae27e29d7922.gif)

**Comment by kwokwilliam** [comment] 2019-06-11 06:46
Duplicate of #17, closed because out of scope for reasons explained in #17

**Closed as completed by kwokwilliam** 2019-06-11 06:46 UTC
Labels: duplicate, Cant fix because of react draft wysiwyg
