### ISSUE TITLE
I don't know who I'm sending my postcard to

### ISSUE THREAD

**Issue by dayoungcheong** [placeholder-team-name/placeholder#2] opened 2019-06-10 23:08 UTC

**Comment by dayoungcheong** [comment] 2019-06-10 23:11
I logged in and went to the recipients tab. I created two different recipients. Then I wrote a postcard, pressed save, pressed preview, then pressed send and the screen indicated that I sent. I have no idea which recipient it was sent to as it never gave me an option to choose which recipient I wanted to send to.

**Comment by kwokwilliam** [comment] 2019-06-11 06:10
While this would be a good quality of life UX change, this was not an initial requirement for us. Low priority, and feature will be added if other more pressing issues have been fixed.

**Comment by clairehjk** [comment] 2019-06-12 17:45
For our deployment in the time give, our intended behavior is that you will be sending the email to everyone in your Recipients page. Again, this is not a bug, more of a feature request so we will be closing this issue.

**Closed as completed by clairehjk** 2019-06-12 17:45 UTC
Labels: enhancement, low priority
